package com.peoplemerge.cohesion.logical;

public enum Operation {

ASK_FOR_HELP,
GO_TO_OZ_AND_CRUSH_WITCH_OF_EAST,
ASK_GLINDA_FOR_HELP_AS_WESTWITCH_THREATENS,
FIND_WIZARD_OF_OZ,
GET_CAPTURED_BY_WITCH,
GET_RESCUED_BY_FRIENDS,
ACCIDENTALLY_KILL_ANOTHER_WITCH,
CLICK_HEELS

}
