package com.peoplemerge.cohesion.communication;

public enum State {

ASKED_FOR_HELP,
GONE_TO_OZ_AND_CRUSHED_WITCH_OF_EAST,

ASK_WITCH_OF_NORTH_FOR_HELP_BEFORE_WITCH_OF_WEST_THREATENS,
FIND_WIZARD_OF_OZ,
GET_CAPTURED_BY_WITCH,
GET_RESCUED_BY_FRIENDS,
ACCIDENTALLY_KILL_ANOTHER_WITCH,
CLICK_HEELS

}
